site_name: rlxnix

repo_url: https://github.com/relacs/relacsed_nix

edit_uri: ""

site_author: Jan Grewe

theme: readthedocs

markdown_extensions:
    - markdown_include.include
    
nav:
    - Home: 'index.html'
    - Installation: 'installation/index.html'
    - Tutorial: 'introduction/index.html'
    - API reference: 'api/index.html'